[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/"
